############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2



[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"



[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Portfolio"
url = "https://abtsegaportfolio.vercel.app/"
external = true

[[main]]
parent = "Pages"
name = "Presetation"
url = "https://www.canva.com/design/DAGWYX-yVjk/HV6egIbrrxAaPsWWG1hZjw/view?utm_content=DAGWYX-yVjk&utm_campaign=designshare&utm_medium=link&utm_source=editor"
external = true






# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
